# Generated by Django 5.0.6 on 2024-08-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shortbio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
