# Generated by Django 5.0.6 on 2024-08-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='profiles.skills'),
        ),
    ]
