# Generated by Django 5.0.6 on 2024-09-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_skills_owner_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiles.profile')),
            ],
        ),
    ]
