# Generated by Django 5.0.6 on 2024-09-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiles.profile'),
        ),
    ]
