# Generated by Django 5.0.6 on 2024-09-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_inbox_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
    ]
