# Generated by Django 5.0.6 on 2024-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
