# Generated by Django 5.0.6 on 2024-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images/ape1.jpg', null=True, upload_to=''),
        ),
    ]
