# Generated by Django 5.0.6 on 2024-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='voteratio',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
