# Generated by Django 5.0.6 on 2024-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_voteratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='ape1.jpg', null=True, upload_to=''),
        ),
    ]
