# Generated by Django 5.0.6 on 2024-09-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_reviews_owner_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
    ]
