# Generated by Django 5.0.6 on 2024-09-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_skills_owner_profile_skills'),
        ('project', '0011_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('owner', 'project')},
        ),
    ]
