# Generated by Django 5.0.6 on 2024-09-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
